version: '3'

services:
  surrealdb:
    image: surrealdb/surrealdb:latest
    restart: always
    command: start --user auth --pass auth file:/surrealdb
    ports:
      - 8000:8000
    volumes:
      - ./volumes/surrealdb:/surrealdb
    networks:
      - cerberust

  mailhog:
    build:
      context: ./mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - cerberust

  cerberust:
    build:
      context: .
    environment:
      - SURREALDB_URL=surrealdb:8000
      - SURREALDB_NS=auth
      - SURREALDB_DB=auth
      - PRIVATE_KEY="./keys/private_key.pem"
      - PUBLIC_KEY="./keys/public_key.pem"
      # 15 minutes
      - ACCESS_TOKEN_EXPIRATION=900
      # 1 day
      - REFRESH_TOKEN_EXPIRATION=86400
    ports:
      - "8080:8080"
    depends_on:
      - surrealdb
    volumes:
      - ./keys:/app/keys
    develop:
      watch:
        - action: rebuild
          path: .
          ignore:
            - target/
            - volumes/
    networks:
      - cerberust
networks:
   cerberust:
