version: '3'

services:
  postgres:
    image: postgres:11.7-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgresql:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      interval: 10s
      retries: 10
      timeout: 2s
    networks:
      - cerberust

  mailhog:
    build:
      context: ./mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - cerberust

  cerberust:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - mailhog
    volumes:
      - ./volumes/keys:/app/keys
    develop:
      watch:
        - action: rebuild
          path: .
          ignore:
            - target/
            - volumes/
    networks:
      - cerberust
networks:
   cerberust:
