version: '3'

services:
  surrealdb:
    image: surrealdb/surrealdb:latest
    restart: always
    command: start --user auth --pass auth file:/surrealdb
    ports:
      - 8000:8000
    volumes:
      - ./volumes/surrealdb:/surrealdb
    networks:
      - cerberust

  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - "4436:4436"
      - "4437:4437"
    networks:
      - cerberust

  cerberust:
    build:
      context: .
    environment:
      - SURREALDB_URL=surrealdb:8000
      - SURREALDB_NS=auth
      - SURREALDB_DB=auth
    ports:
      - "8080:8080"
    depends_on:
      - surrealdb
    develop:
      watch:
        - action: rebuild
          path: .
          ignore:
            - target/
            - volumes/
    networks:
      - cerberust
networks:
   cerberust:
